medical_clinic/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('patients/', include('patients.urls')),
    # Dodaj tutaj inne adresy URL dla innych aplikacji, jeśli istnieją
]

patients/urls.py
from django.urls import path
from . import views


app_name = 'patients'

urlpatterns = [
    path('', views.patient_list, name='patient_list'),
    path('new/', views.patient_new, name='patient_new'),
    # path('<int:pk>/', views.patient_detail, name='patient_detail'),
    # path('<int:pk>/', views.patient_edit, name='patient_edit'),
    path('<int:patient_id>/edit/', views.edit_patient_and_address, name='edit_patient_and_address'),
    path('<int:pk>/delete/', views.patient_delete, name='patient_delete'),
]

patients/models.py
import datetime
from django.db import models
from django.utils import timezone


class Patient(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    pesel = models.CharField(max_length=11)
    pub_date = models.DateTimeField("date published")

    def __str__(self):
        return f"{self.first_name} {self.last_name}, PESEL: {self.pesel}"

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    def update_patient(self, first_name, last_name, pesel):
        self.first_name = first_name
        self.last_name = last_name
        self.pesel = pesel
        self.save()


class Address(models.Model):
    street = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    zipcode = models.CharField(max_length=5)
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)

    def __str__(self):
        return self.city

    def update_address(self, street, city, zipcode):
        self.street = street
        self.city = city
        self.zipcode = zipcode
        self.save()

patients/forms.py
from django import forms
from .models import Patient, Address
from datetime import date


class PatientForm(forms.ModelForm):
    pub_date = forms.DateField(initial=date.today)

    class Meta:
        model = Patient
        fields = ['first_name', 'last_name', 'pesel', 'pub_date']


class AddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = ['street', 'city', 'zipcode']

patients/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Patient, Address
from .forms import PatientForm, AddressForm

import logging
logger = logging.getLogger(__name__)


def patient_list(request):
    sort_by = request.GET.get('sort_by')
    #download data from models
    patients = Patient.objects.all()
    addresses = Address.objects.all()

        #sorting
    if sort_by == 'first_name_asc':
        patients = patients.order_by('first_name')
    elif sort_by == 'first_name_desc':
        patients = patients.order_by('-first_name')
    elif sort_by == 'last_name_asc':
        patients = patients.order_by('last_name')
    elif sort_by == 'last_name_desc':
        patients = patients.order_by('-last_name')

        #assigning addresses to patients
    for patient in patients:
        patient.address = addresses.filter(patient=patient).first()

        #searching
    search_query = request.GET.get('search')
    if search_query:
        patients = patients.filter(first_name__icontains=search_query) | patients.filter(last_name__icontains=search_query)

    patient_form = PatientForm()
    address_form = AddressForm()

    if request.method == 'POST':
        patient_form = PatientForm(request.POST)
        address_form = AddressForm(request.POST)
        if patient_form.is_valid() and address_form.is_valid():
            patient = patient_form.save()
            address = address_form.save(commit=False)
            address.patient = patient
            address.save()
            return redirect('patients:patient_list')

    return render(request, 'patients/patient_list.html', {'patients': patients, 'patient_form': patient_form, 'address_form': address_form})

def patient_detail(request, pk):
    patient = get_object_or_404(Patient, pk=pk)
    address = patient.address_set.first()
    print(address)
    logger.info(address)
    return render(request, 'patients/patient_detail.html', {'patient': patient, 'address': address})


def patient_new(request):
    if request.method == "POST":
        patient_form = PatientForm(request.POST)
        address_form = AddressForm(request.POST)
        if patient_form.is_valid() and address_form.is_valid():
            patient = patient_form.save()
            address = address_form.save(commit=False)
            address.patient = patient
            address.save()
            return redirect('patient_detail', pk=patient.pk)
    else:
        patient_form = PatientForm()
        address_form = AddressForm()
    return render(request, 'patients/patient_edit.html', {'patient_form': patient_form, 'address_form': address_form})

def edit_patient_and_address(request, patient_id):
    patient = get_object_or_404(Patient, pk=patient_id)
    address = patient.address_set.first()
    if request.method == "POST":
        patient_form = PatientForm(request.POST, instance=patient)
        address_form = AddressForm(request.POST, instance=address)
        if patient_form.is_valid() and address_form.is_valid():
            patient_form.save()
            address_form.save()
            return redirect('patients:patient_list')  #redirect to the main view
    else:
        patient_form = PatientForm(instance=patient)
        address_form = AddressForm(instance=address)
    return render(request, 'patients/edit_patient_and_address.html',
                  {'patient_form': patient_form, 'address_form': address_form})

def patient_delete(request, pk):
    patient = get_object_or_404(Patient, pk=pk)
    if request.method == 'POST':
        patient.delete()
        return redirect('patients:patient_list')  # redirect to the main view
    return render(request, 'patients/patient_confirm_delete.html', {'patient': patient})

patients/templates/patients/edit_patient_and_address.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Medical Clinic</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto&display=swap">

    <style>
    .form-container {
        display: flex;
        justify-content: center;
        align-items: center;
        margin-left: auto;
        margin-right: 35%;
        margin-top: 10vh;
        height: 60vh;
        width: 320px;
    }
    .form-content {
        text-align: center;
    }

</style>

</head>
<body>
    <h1>Medical Clinic</h1>

        <!-- adding patient form -->
        <div class="form-container" >
            <div class="form-content">
            <form method="post">
                {% csrf_token %}
                <h2>Edit data:</h2>
                <h3>Personal data:</h3>
                {{ patient_form.as_p }}
                <h3>Address:</h3>
                {{ address_form.as_p }}
                <button type="submit" style="display: block; margin: 0 auto; font-size:16px;">Edit</button>
            </form>
            <hr>
        </div>
    </div>

    <script>
        function savePatientData(button) {
            var row = button.parentNode.parentNode;
            var firstName = row.cells[0].innerText.trim();
            var lastName = row.cells[0].innerText.trim();
            var pesel = row.cells[1].innerText.trim();
            var street = row.cells[2].querySelector('span').innerText.trim();
            var cityZip = row.cells[2].querySelectorAll('span')[1].innerText.trim().split(', ');
            var city = cityZip[0];
            var zipcode = cityZip[1];
            // saving changes in a database
        }

        function deletePatient(button) {
            var row = button.parentNode.parentNode;
            // delate patients
        }
    </script>
</body>
</html>

patients/templates/patients/patient_confirm_delete.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Medical Clinic</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto&display=swap">

    <style>
    .modal {
        display: flex;
        align-items: center;
        justify-content: center;
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background-color: rgba(0, 0, 0, 0.5);
        z-index: 9999;
    }

    .modal-content {
        text-align: center;
        background-color: #fff;
        padding: 20px;
        border-radius: 10px;
        border: 2px solid #ccc;
    }

    #confirm-delete-yes,
    #confirm-delete-no {
        margin-top: 10px;
        padding: 5px 10px;
        border: none;
        background-color: #4CAF50;
        color: #fff;
        cursor: pointer;
        border-radius: 5px;
    }

    #confirm-delete-yes:hover,
    #confirm-delete-no:hover {
        background-color: #00A36C;
    }
</style>

</head>
<body>
    <h1>Medical Clinic</h1>

    <!-- confirm  -->
    <div id="confirm-delete-modal" class="modal">
        <div class="modal-content">
            <p>Are you sure you want to remove the patient?</p>
            <button id="confirm-delete-yes">Yes</button>
            <button id="confirm-delete-no">No</button>
        </div>
    </div>
<script>
    document.addEventListener('DOMContentLoaded', function() {
        var confirmDeleteModal = document.getElementById('confirm-delete-modal');
        var confirmDeleteYes = document.getElementById('confirm-delete-yes');
        var confirmDeleteNo = document.getElementById('confirm-delete-no');

        confirmDeleteYes.addEventListener('click', function() {
            confirmDeleteModal.style.display = 'none';

            var pk = '{{ patient.pk }}'; // patient id
            var formData = new FormData();
            formData.append('pk', pk);
            var xhr = new XMLHttpRequest();
            xhr.open('POST', window.location.href, true);
            xhr.setRequestHeader('X-CSRFToken', '{{ csrf_token }}');
            xhr.onload = function() {
                if (xhr.status === 200) {
                    //redirect to the main view
                    window.location.href = '{% url 'patients:patient_list' %}';
                }
            };
            xhr.send(formData);
        });

        confirmDeleteNo.addEventListener('click', function() {
            //redirect to the main view
            window.location.href = '{% url 'patients:patient_list' %}';
        });
    });
</script>



</body>
</html>

patients/templates/patients/patient_detail.html
{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>Szczegóły pacjenta</title>#}
{#</head>#}
{#<body>#}
{#    <h1>Szczegóły pacjenta</h1>#}
{#    <ul>#}
{#        <li><strong>Imię:</strong> {{ patient.first_name }}</li>#}
{#        <li><strong>Nazwisko:</strong> {{ patient.last_name }}</li>#}
{#        <li><strong>PESEL:</strong> {{ patient.pesel }}</li>#}
{#        <!-- Dodajemy przycisk do edycji -->#}
{#        <li><a href="{% url 'patients:patient_edit' patient.pk %}">Edytuj</a></li>#}
{#        {% if address %}#}
{#            <li><strong>Ulica:</strong> {{ address.street }}</li>#}
{#            <li><strong>Miasto:</strong> {{ address.city }}</li>#}
{#            <li><strong>Kod pocztowy:</strong> {{ address.zipcode }}</li>#}
{#        {% endif %}#}
{#    </ul>#}
{#</body>#}
{#</html>#}

patients/templates/patients/patient_edit.html
{#<!-- patients/patient_edit.html -->#}
{##}
{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>Edycja pacjenta</title>#}
{#</head>#}
{#<body>#}
{#    <h1>Edycja pacjenta</h1>#}
{#    <form method="post">#}
{#        {% csrf_token %}#}
{#        <h2>Dane pacjenta:</h2>#}
{#        {{ patient_form.as_p }}#}
{#        <h2>Adres:</h2>#}
{#        {{ address_form.as_p }}#}
{#        <button type="submit">Zapisz zmiany</button>#}
{#    </form>#}
{#</body>#}
{#</html>#}

patients/templates/patients/patient_form.html
{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>Add/Edit Patient</title>#}
{#</head>#}
{#<body>#}
{#    <h1>Add/Edit Patient</h1>#}
{#    <form method="post">#}
{#        {% csrf_token %}#}
{#        {{ patient_form.as_p }}#}
{#        {{ address_form.as_p }}#}
{#        <button type="submit">Save</button>#}
{#    </form>#}
{#</body>#}
{#</html>#}

patients/templates/patients/patient_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Medical Clinic</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto&display=swap">

     <style>
        /* date and time style */
        #current-date-time {
            position: fixed;
            top: 10px;
            right: 10px;
            font-size: 14px;
            color: white;
        }
    </style>

</head>
<body>
    <h1>Medical Clinic</h1>

    <div class="container">
        <!-- sort and search -->
        <div class="sorting-search-form">
            <h2>Pacients list:</h2>
            <form method="get">
                <label for="sort_by">Sort by:</label>
                <select name="sort_by" id="sort_by">
                    <option value="first_name_asc">Name ASC</option>
                    <option value="first_name_desc">Name DESC</option>
                    <option value="last_name_asc">Surname ASC</option>
                    <option value="last_name_desc">Surname DESC</option>
                </select>
                <button type="submit">Sort</button>
            </form>
            <form method="get">
                <label for="search">Search:</label>
                <input type="text" name="search" id="search">
                <button type="submit">Search | Restore</button>
            </form>
        </div>

        <!-- table/ list of patients -->
        <div class="patient-list">
            <table>
                <tr>
                    <th style="width: 30%;">Name</th>
                    <th style="width: 20%;">Pesel</th>
                    <th style="width: 35%;">Address</th>
                    <th style="width: 15%;">Actions</th>
                </tr>
                {% for patient in patients %}
                    <tr>
                        <!-- personal data -->
                        <td>{{ patient.first_name }} {{ patient.last_name }}</td>
                        <td>{{ patient.pesel}}</td>

                        <td>
                            <!-- address -->
                            {% if patient.address %}
                                {{ patient.address.street }}<br>
                                <span class="address">{{ patient.address.city }}, {{ patient.address.zipcode }}</span>
                            {% endif %}
                        </td>
                        <td>
                            <!-- editing and delating icons -->
                            <a href="{% url 'patients:edit_patient_and_address' patient.pk %}" class="button-icon">
                                <i class="fas fa-pencil-alt icon"></i>
                            </a>

                            <a href="{% url 'patients:patient_delete' patient.pk %}" class="button-icon2">
                                <i class="fas fa-times icon"></i>
                            </a>

                        </td>
                    </tr>
                {% endfor %}
            </table>
        </div>

        <!-- adding patient form -->
        <div class="form-container">
            <form method="post">
                {% csrf_token %}
                <h2 class="green">Add new patient:</h2>
                <h3>Personal data:</h3>
                <hr>
                {{ patient_form.as_p }}
                <h3>Address:</h3>
                <hr>
                {{ address_form.as_p }}
                <button type="submit" style="display: block; margin: 0 auto; font-size:16px;">Add</button>
            </form>


        </div>
    </div>
<div id="current-date-time"></div>
    <!-- date and time -->
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            // actualization
            function updateDateTime() {
                var currentDateTime = new Date();
                var formattedDateTime = currentDateTime.toLocaleString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric', hour: 'numeric', minute: 'numeric', second: 'numeric', hour12: true });
                document.getElementById('current-date-time').innerText = formattedDateTime;
            }

            updateDateTime();
            setInterval(updateDateTime, 1000);
        });
    </script>
</body>
</html>